Update File Header Copyright Years
wpilibsuite/cameraserver pull request #81
Opened 2017-07-10 03:44 UTC by karagenit

2017-07-10 03:44 UTC, frcjenkins commented
Can one of the admins verify this patch?

2017-07-24 15:08 UTC, JLLeitschuh submitted a review, later dismissed

2017-07-24 17:40 UTC, calcmogul commented
These should be using year ranges. For example, `2015' should be replaced with `2015-2017` instead of `2017`. We need to set up wpiformat with this repo at some point.

2017-07-24 17:44 UTC, calcmogul requested changes
See the comment I made above as well.

2017-07-24 17:44 UTC, calcmogul commented on src/NetworkListener.h
> +/* Copyright (c) FIRST 2017-2016. All Rights Reserved.                        */
Um, the range is backwards. This happened in a few other spots too.

2017-07-30 20:12 UTC, frcjenkins commented
Can one of the admins verify this patch?

2017-07-30 20:14 UTC, karagenit commented on src/NetworkListener.h
> +/* Copyright (c) FIRST 2017-2016. All Rights Reserved.                        */
Yeah, that happened because the regex I wrote just matched "FIRST 201x" and replaced it with "FIRST 2017" - it was ignoring the "-2016" after that.

2017-07-30 20:18 UTC, karagenit commented
Should be fixed now, I rewrote the script to use the "2016-2017" style.

Searching this repo on github shows 66 files with a copyright header (not including the various Google ones), so I think all of them are updated.

Something kind of odd, the `license.txt` file has the FIRST/YEAR backwards from all of the other source files. I dunno if that's intentional or not, so I left it as-is, but it would be a quick fix.

2017-07-30 22:12 UTC, calcmogul commented
The ends of the comment lines should line up, by the way.

I appreciate you working on this, but wpiformat solves this whole class of problems. #86 adds wpiformat support to this repo. It performs a lot of mundane tasks automatically like updating the copyright years correctly and makes changing the year ordering trivial. Eventually, almost all the warnings cpplint.py produces will be automatically fixed by wpiformat as well.

2017-07-31 02:06 UTC, karagenit commented
No problemo, it was just a couple of `sed` commands to change all of them. If you'd like, I could pretty easily modify it to also fix the spacing so the comment lines are aligned properly, but it sounds like wpiformat is a better option so feel free to just close this PR.

2017-08-01 21:21 UTC, closed without merging